name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JDK_VERSION: 21
      MAVEN_VERSION: 3.9.6

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'maven'
          java-version: ${{ env.JDK_VERSION }}
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: 查看运行环境
        run: mvn -v

      - name: 查看是否有java环境
        run: java -version

      - name: 打包
        run: mvn package

      - name: 运行多行的shell命令
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls
          pwd